import Head from 'next/head'
import Main from '../comps/Main'
import Top from '../comps/Top'
export default function Home() {
  return (
    <div className="antialiased bg-[#c5e4e7] lg:h-[120vh] sm:h-[100vh]">
      <Head>
        <title>Calculator App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   <div>
     <Top/>
     <Main/>
   </div>


    </div>
  )
}
